# Generated by Django 5.2.4 on 2025-12-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('SURVEY', 'Survey'), ('REVIEW', 'Review')], default='SYSTEM', max_length=10),
        ),
    ]
